# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PicoTeleop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PicoTeleop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10PicoTeleop.proto\"\x1c\n\x04Vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"?\n\x0bTrackerPose\x12\x17\n\x08position\x18\x01 \x01(\x0b\x32\x05.Vec3\x12\x17\n\x08rotation\x18\x02 \x01(\x0b\x32\x05.Quat\"\xe4\x01\n\nController\x12\x12\n\nmenuButton\x18\x01 \x01(\x08\x12\x15\n\rtriggerButton\x18\x02 \x01(\x08\x12\x14\n\x0ctriggerValue\x18\t \x01(\x02\x12\x12\n\ngripButton\x18\x03 \x01(\x08\x12\x11\n\tgripValue\x18\n \x01(\x02\x12\x11\n\tjoyButton\x18\x04 \x01(\x08\x12\x17\n\x08joyValue\x18\x0b \x01(\x0b\x32\x05.Vec2\x12\x0f\n\x07xButton\x18\x05 \x01(\x08\x12\x0f\n\x07yButton\x18\x06 \x01(\x08\x12\x0f\n\x07\x61\x42utton\x18\x07 \x01(\x08\x12\x0f\n\x07\x62\x42utton\x18\x08 \x01(\x08\"\x94\x01\n\tGloveHand\x12\x0f\n\x07\x61\x42utton\x18\x01 \x01(\x08\x12\x0f\n\x07\x62\x42utton\x18\x02 \x01(\x08\x12\x12\n\nmenuButton\x18\x04 \x01(\x08\x12\x11\n\tjoyButton\x18\x03 \x01(\x08\x12\x1a\n\x0bjoyPosition\x18\x05 \x01(\x0b\x32\x05.Vec2\x12\x12\n\x03imu\x18\x06 \x01(\x0b\x32\x05.Quat\x12\x0e\n\x06joints\x18\x07 \x03(\x02\"\xd8\x02\n\nTeleopData\x12\x19\n\x03HMD\x18\x01 \x01(\x0b\x32\x0c.TrackerPose\x12(\n\x12LeftControllerPose\x18\x02 \x01(\x0b\x32\x0c.TrackerPose\x12)\n\x13RightControllerPose\x18\x03 \x01(\x0b\x32\x0c.TrackerPose\x12\x1e\n\x08Trackers\x18\x04 \x03(\x0b\x32\x0c.TrackerPose\x12#\n\x0eLeftController\x18\x05 \x01(\x0b\x32\x0b.Controller\x12$\n\x0fRightController\x18\x06 \x01(\x0b\x32\x0b.Controller\x12\x1c\n\x08LeftHand\x18\x07 \x01(\x0b\x32\n.GloveHand\x12\x1d\n\tRightHand\x18\x08 \x01(\x0b\x32\n.GloveHand\x12\x11\n\tTimeStamp\x18\t \x01(\x03\x12\x12\n\nFrameIndex\x18\n \x01(\x04\x12\x0b\n\x03MSG\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PicoTeleop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEC2']._serialized_start=20
  _globals['_VEC2']._serialized_end=48
  _globals['_VEC3']._serialized_start=50
  _globals['_VEC3']._serialized_end=89
  _globals['_QUAT']._serialized_start=91
  _globals['_QUAT']._serialized_end=141
  _globals['_TRACKERPOSE']._serialized_start=143
  _globals['_TRACKERPOSE']._serialized_end=206
  _globals['_CONTROLLER']._serialized_start=209
  _globals['_CONTROLLER']._serialized_end=437
  _globals['_GLOVEHAND']._serialized_start=440
  _globals['_GLOVEHAND']._serialized_end=588
  _globals['_TELEOPDATA']._serialized_start=591
  _globals['_TELEOPDATA']._serialized_end=935
# @@protoc_insertion_point(module_scope)
