# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import importlib
import threading
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import (
    RealSenseCameraConfig,
)  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from .lerobot_dataset import LeRobotDataset
from .image_writer import safe_stop_image_writer
try:
    from lerobot.datasets.feature_utils import build_dataset_frame
except ImportError:
    from lerobot.datasets.utils import build_dataset_frame
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import Robot, RobotConfig  # noqa: F401
from lerobot.teleoperators import TeleoperatorConfig  # noqa: F401
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from .runtime_helpers import build_dataset_features
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data

from lerobot_play._compat import Teleoperator
from lerobot_play.robots.utils import make_robot_from_config
from lerobot_play.teleoperators.utils import make_teleoperator_from_config
from lerobot_play.utils.display_filter import filter_display_observation
from lerobot_play.utils.rerun_control_display import configure_control_rerun_display

DEFAULT_RECORD_PREVIEW_FPS = 5.0


def _get_multi_teleop_arm_types() -> tuple[type, ...]:
    leader_specs = (
        ("lerobot.teleoperators.so_leader.so_leader", ("SO100Leader", "SO101Leader")),
        ("lerobot.teleoperators.koch_leader.koch_leader", ("KochLeader",)),
    )
    leader_types: list[type] = []
    for module_name, class_names in leader_specs:
        try:
            module = importlib.import_module(module_name)
        except Exception:
            continue

        for class_name in class_names:
            leader_cls = getattr(module, class_name, None)
            if isinstance(leader_cls, type):
                leader_types.append(leader_cls)

    return tuple(leader_types)


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(
                policy_path, cli_overrides=cli_overrides
            )
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError(
                "Choose a policy, a teleoperator or both to control the robot"
            )

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""

class _RecordPreviewWorker:
    def __init__(self, preview_fps: float = DEFAULT_RECORD_PREVIEW_FPS):
        self.preview_fps = preview_fps
        self._lock = threading.Lock()
        self._wake_event = threading.Event()
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        self._latest_payload: dict[str, Any] | None = None
        self._last_preview_timestamp_s: float | None = None

    def start(self) -> None:
        if self.preview_fps <= 0 or is_headless():
            return

        if self._thread is not None and self._thread.is_alive():
            return

        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._run,
            name="record-preview-worker",
            daemon=True,
        )
        self._thread.start()

    def submit(
        self,
        observation: dict[str, Any],
        camera_keys: list[str],
        episode_index: int | None,
        total_episodes: int | None,
        frame_index: int,
        timestamp_s: float,
        action: RobotAction,
    ) -> None:
        if self._thread is None:
            return

        with self._lock:
            self._latest_payload = {
                "observation": observation,
                "timestamp_s": timestamp_s,
                "action": action,
            }
            self._wake_event.set()

    def stop(self) -> None:
        self._stop_event.set()
        self._wake_event.set()
        if self._thread is not None:
            self._thread.join(timeout=1.0)
            self._thread = None

    def _run(self) -> None:
        while not self._stop_event.is_set():
            self._wake_event.wait(timeout=0.1)
            self._wake_event.clear()
            if self._stop_event.is_set():
                break

            payload = self._consume_latest_payload()
            if payload is None:
                continue

            timestamp_s = float(payload["timestamp_s"])
            if not self._should_render(timestamp_s):
                continue

            log_rerun_data(
                observation=payload["observation"],
                action=payload["action"],
            )
            self._last_preview_timestamp_s = timestamp_s

    def _consume_latest_payload(self) -> dict[str, Any] | None:
        with self._lock:
            payload = self._latest_payload
            self._latest_payload = None
        return payload

    def _should_render(self, timestamp_s: float) -> bool:
        if self.preview_fps <= 0:
            return False

        if self._last_preview_timestamp_s is None:
            return True

        return (timestamp_s - self._last_preview_timestamp_s) >= (
            1.0 / self.preview_fps
        )


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    use_mcap: bool = False,
    online_encoding: bool = False,
    episode_index: int | None = None,
    total_episodes: int | None = None,
    task_switch_coordinator=None,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    if dataset is not None:
        loop_dataset_features = dataset.features
    else:
        loop_dataset_features = build_dataset_features(robot, use_videos=True)

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_arm_types = _get_multi_teleop_arm_types()
        teleop_keyboard = next(
            (t for t in teleop if isinstance(t, KeyboardTeleop)), None
        )
        teleop_arm = next(
            (
                t
                for t in teleop
                if teleop_arm_types and isinstance(t, teleop_arm_types)
            ),
            None,
        )

        if not (
            teleop_arm
            and teleop_keyboard
            and len(teleop) == 2
            and robot.name == "lekiwi_client"
        ):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    frame_index = 0
    timestamp = 0
    current_task = single_task
    start_episode_t = time.perf_counter()
    camera_keys = list(getattr(robot, "cameras", {}).keys())
    preview_worker = _RecordPreviewWorker() if display_data else None
    if preview_worker is not None:
        preview_worker.start()
    try:
        while timestamp < control_time_s:
            start_loop_t = time.perf_counter()

            if events["exit_early"]:
                events["exit_early"] = False
                break

            if events.get("reset_robot"):
                logging.info("Reset event received. Moving robot to configured reset pose.")
                robot.reset_zero()
                events["reset_robot"] = False
                if isinstance(teleop, Teleoperator) and hasattr(teleop, "reset_pose"):
                    teleop.reset_pose()
                start_episode_t = time.perf_counter()
                timestamp = 0
                continue

            # Get robot observation
            try:
                obs = robot.get_observation()
            except Exception as exc:
                logging.error(
                    "Camera read failed during recording; stopping current episode without saving partial data: %s",
                    exc,
                )
                if dataset is not None:
                    dataset.clear_episode_buffer(restart_image_writer=True)
                events["discard_episode"] = True
                events["stop_recording"] = True
                events["exit_early"] = True
                break

            # Applies a pipeline to the raw robot observation, default is IdentityProcessor
            obs_processed = robot_observation_processor(obs)

            if policy is not None or dataset is not None:
                observation_frame = build_dataset_frame(
                    loop_dataset_features, obs_processed, prefix=OBS_STR
                )

            # Get action from either policy or teleop
            if (
                policy is not None
                and preprocessor is not None
                and postprocessor is not None
            ):
                if task_switch_coordinator is not None:
                    action_queue = getattr(policy, "_action_queue", None)
                    is_switch_boundary = action_queue is None or len(action_queue) == 0
                    current_task = task_switch_coordinator.maybe_switch(
                        is_switch_boundary=is_switch_boundary
                    ).task_description

                action_values = predict_action(
                    observation=observation_frame,
                    policy=policy,
                    device=get_safe_torch_device(policy.config.device),
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    use_amp=policy.config.use_amp,
                    task=current_task,
                    robot_type=robot.robot_type,
                )

                act_processed_policy: RobotAction = make_robot_action(
                    action_values, loop_dataset_features
                )

            elif policy is None and isinstance(teleop, Teleoperator):
                act = teleop.get_action()

                # Applies a pipeline to the raw teleop action, default is IdentityProcessor
                act_processed_teleop = teleop_action_processor((act, obs))

            elif policy is None and isinstance(teleop, list):
                arm_action = teleop_arm.get_action()
                arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
                keyboard_action = teleop_keyboard.get_action()
                base_action = robot._from_keyboard_to_base_action(keyboard_action)
                act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
                act_processed_teleop = teleop_action_processor((act, obs))
            else:
                logging.info(
                    "No policy or teleoperator provided, skipping action generation."
                    "This is likely to happen when resetting the environment without a teleop device."
                    "The robot won't be at its rest position at the start of the next episode."
                )
                continue

            # Applies a pipeline to the action, default is IdentityProcessor
            if policy is not None and act_processed_policy is not None:
                robot_action_to_send = robot_action_processor((act_processed_policy, obs))
            else:
                robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

            # Send action to robot
            # Action can eventually be clipped using `max_relative_target`,
            # so the robot return value is the source of truth for dataset logging.
            # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
            sent_action = robot.send_action(robot_action_to_send)

            # Write to dataset
            if dataset is not None:
                action_frame = build_dataset_frame(
                    dataset.features, sent_action, prefix=ACTION
                )
                frame = {**observation_frame, **action_frame, "task": single_task}
                try:
                    dataset.add_frame(frame, use_mcap, online_encoding)
                except Exception as exc:
                    logging.error(
                        "Dataset write failed during recording; stopping current episode without saving partial data: %s",
                        exc,
                    )
                    dataset.clear_episode_buffer(restart_image_writer=True)
                    events["discard_episode"] = True
                    events["stop_recording"] = True
                    events["exit_early"] = True
                    break

            if preview_worker is not None:
                display_observation = filter_display_observation(obs_processed, camera_keys)
                preview_worker.submit(
                    observation=display_observation,
                    camera_keys=camera_keys,
                    episode_index=episode_index,
                    total_episodes=total_episodes,
                    frame_index=frame_index,
                    timestamp_s=frame_index / fps,
                    action=sent_action,
                )

            dt_s = time.perf_counter() - start_loop_t
            precise_sleep(1 / fps - dt_s)

            frame_index += 1
            timestamp = time.perf_counter() - start_episode_t
    finally:
        if preview_worker is not None:
            preview_worker.stop()


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    if cfg.display_data:
        configure_control_rerun_display(robot)
    teleop = (
        make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None
    )

    (
        teleop_action_processor,
        robot_action_processor,
        robot_observation_processor,
    ) = make_default_processors()

    dataset_features = build_dataset_features(robot, use_videos=cfg.dataset.video)

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera
                * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(
            dataset, robot, cfg.dataset.fps, dataset_features
        )
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera
            * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Load pretrained policy
    policy = (
        None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
    )
    preprocessor = None
    postprocessor = None
    if cfg.policy is not None:
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while (
            recorded_episodes < cfg.dataset.num_episodes
            and not events["stop_recording"]
        ):
            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1)
                or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer(restart_image_writer=True)
                continue

            if events.get("discard_episode"):
                events["discard_episode"] = False
                events["exit_early"] = False
                continue

            dataset.save_episode()
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
