# O10 双臂控制配置
# 供脚本 `./scripts/o10/dual_arm/control_o10_dual.sh` 使用。

teleop:
  type: pico_leader_dual_arm_agibot_o10
  id: pico_dual
  vr_pose_port: 8000
  vr_ctrl_port: 8001
  vr_device: pico  # pico_wrist, pico
  enable_hand: true  # true, false
  arm_trigger_mode: left  # split, left, right, both
  hand_mode: trigger_gesture  # glove, trigger_gesture
  trigger_gesture: tripod  # pinch, tripod（仅 trigger_gesture 模式生效）
  action_control_mode: joint  # joint, eef_delta
  hand_action_mode: gripper_1d  # dexterous_10d, gripper_1d
  left:
    handedness: left
    wrist_pose_source: left  # auto, left, right
    trigger_gesture: tripod
    gripper_gesture: tripod
    reset_poses_path: ~/workspace/arm-hand-teleop/configs/reset_poses/o10_dual_reset.json
    reset_gesture: pinch
  right:
    handedness: right
    wrist_pose_source: right  # auto, left, right
    trigger_gesture: pinch
    gripper_gesture: pinch
    reset_poses_path: ~/workspace/arm-hand-teleop/configs/reset_poses/o10_dual_reset.json
    reset_gesture: pinch

robot:
  type: pico_follower_dual_arm_agibot_o10
  id: o10_dual
  enable_hand: true  # true, false
  action_control_mode: joint  # joint, eef_delta
  hand_action_mode: gripper_1d  # dexterous_10d, gripper_1d
  allow_camera_read_failures: true
  left:
    port: can0  # CAN 口
    handedness: left
    channel_mode: multiChannel  # multiChannel, multiCan
    device_id: 1
    canfd_id: 0
    channel_id: null  # null 自动: left->0, right->1
    gripper_gesture: tripod
    reset_poses_path: ~/workspace/arm-hand-teleop/configs/reset_poses/o10_dual_reset.json
    reset_gesture: pinch
  right:
    port: can1  # CAN 口
    handedness: right
    channel_mode: multiChannel  # multiChannel, multiCan
    device_id: 1
    canfd_id: 0
    channel_id: null  # null 自动: left->0, right->1
    gripper_gesture: pinch
    reset_poses_path: ~/workspace/arm-hand-teleop/configs/reset_poses/o10_dual_reset.json
    reset_gesture: pinch
  cameras:
    top:
      type: opencv  # opencv, intelrealsense
      index_or_path: /dev/v4l/by-id/usb-LRCP_500W_LRCP_500W_200901010001-video-index0
      width: 640
      height: 480
      fps: 30
      fourcc: MJPG
      rotation: NO_ROTATION  # NO_ROTATION, ROTATE_90, ROTATE_180, ROTATE_270
    left_wrist:
      type: intelrealsense
      serial_number_or_name: "260322276846"
      width: 640
      height: 480
      fps: 30
      use_depth: false
      color_mode: rgb
      rotation: NO_ROTATION
    right_wrist:
      type: intelrealsense
      serial_number_or_name: "260322273018"
      width: 640
      height: 480
      fps: 30
      use_depth: false
      color_mode: rgb
      rotation: NO_ROTATION

fps: 30
display_data: true  # true, false
display_terminal: false  # true, false
