# O10 单臂推理配置：PI0
# 模型：pi0/038393/pretrained_model

infer:
  policy: pi0
  task_description: pick blue camera from yellow paper into black tray
  model_path: ~/workspace/mymodels/agi_arm_bot/pi0/038393/pretrained_model
  save_data: false
  async_infer: false
  num_episodes: 1
  episode_time_sec: 30
  fps: 30
  device: cuda
  server_address: localhost:8080
  save_path: null

robot:
  type: pico_follower_single_arm_agibot_o10
  port: can0
  id: o10_right
  handedness: right
  channel_mode: multiChannel
  device_id: 1
  canfd_id: 0
  channel_id: null
  arm_reset_joints_path: ~/workspace/arm-hand-teleop/configs/o10_right_reset_pose.json
  hand_reset_joints_path: ~/workspace/arm-hand-teleop/configs/o10_right_reset_pose.json

  cameras:
    right:
      type: realsense
      serial_number_or_name: "260322273018"
      width: 640
      height: 480
      fps: 30
      use_depth: false
      color_mode: RGB
      rotation: NO_ROTATION

    top:
      type: opencv
      index_or_path: /dev/v4l/by-id/usb-LRCP_500W_LRCP_500W_200901010001-video-index0
      width: 640
      height: 480
      fps: 30
      rotation: NO_ROTATION
